package domain.EntidadesOrganizacionales.CategoriaEmpresa;

public enum Rubro {
    ELECTRICIDAD, GAS, VAPOR, AIRE_ACONDICIONADO, SUMINISTRO_DE_AGUA, CLOACAS, GESTION_DE_RESIDUOS_Y_RECUPERACION_DE_MATERIALES,
    SERVICIO_DE_TRANSPORTE_Y_ALMACENAMIENTO, SERVICIO_DE_ALOJAMIENTO, SERVICIO_DE_COMIDA, INFORMACION_Y_COMUNICACIONES, INTERMEDIACION_FINANCIERA,
    SERVICIOS_DE_SEGUROS, SERVICIOS_INMOBILIARIOS, SERVICIOS_PROFESIONALES, SERVICIOS_CIENTIFICOS, SERVICIOS_TECNICOS, ACTIVIDADES_ADMINISTRATIVAS,
    SERVICIOS_DE_APOYO, ENSENIANZA, SALUD_HUMANA, SERVICIOS_SOCIALES, SERVICIOS_ARTISTICOS, SERVICIOS_CULTURALES, SERVICIOS_DEPORTIVOS,
    SERVICIOS_DE_ESPARCIMIENTO, SERVICIOS_DE_ASOCIACIONES, SERVICIOS_PERSONALES,
    CONSTRUCCION,
    COMERCIO, REPARACION_DE_VEHICULOS_AUTOMOTORES_Y_BICICLETAS,
    INDUSTRIA_MANUFACTURERA, //SERVICIO_DE_TRANSPORTE_Y_ALMACENAMIENTO, INFORMACION_Y_COMUNICACIONES, // -> YA DECLARADO
    EXPLOTACION_DE_MINAS, CANTERAS,
    AGRICULTURA, GANADERIA, CAZA, SILVICULTURA, PESCA
}
