package domain.EntidadesOrganizacionales.CategoriaEmpresa;

public enum Sector {
    SERVICIO(new Rubro[]{Rubro.ELECTRICIDAD, Rubro.GAS, Rubro.VAPOR, Rubro.AIRE_ACONDICIONADO, Rubro.SUMINISTRO_DE_AGUA, Rubro.CLOACAS,
            Rubro.GESTION_DE_RESIDUOS_Y_RECUPERACION_DE_MATERIALES, Rubro.SERVICIO_DE_TRANSPORTE_Y_ALMACENAMIENTO, Rubro.SERVICIO_DE_ALOJAMIENTO,
            Rubro.SERVICIO_DE_COMIDA, Rubro.INFORMACION_Y_COMUNICACIONES, Rubro.INTERMEDIACION_FINANCIERA,
            Rubro.SERVICIOS_DE_SEGUROS, Rubro.SERVICIOS_INMOBILIARIOS, Rubro.SERVICIOS_PROFESIONALES, Rubro.SERVICIOS_CIENTIFICOS, Rubro.SERVICIOS_TECNICOS,
            Rubro.ACTIVIDADES_ADMINISTRATIVAS, Rubro.SERVICIOS_DE_APOYO, Rubro.ENSENIANZA, Rubro.SALUD_HUMANA, Rubro.SERVICIOS_SOCIALES,
            Rubro.SERVICIOS_ARTISTICOS, Rubro.SERVICIOS_CULTURALES, Rubro.SERVICIOS_DEPORTIVOS,
            Rubro.SERVICIOS_DE_ESPARCIMIENTO, Rubro.SERVICIOS_DE_ASOCIACIONES, Rubro.SERVICIOS_PERSONALES}),
    CONSTRUCCION(new Rubro[]{Rubro.CONSTRUCCION}),
    COMERCIO(new Rubro[]{Rubro.COMERCIO,Rubro.REPARACION_DE_VEHICULOS_AUTOMOTORES_Y_BICICLETAS}),
    INDUSTRIA(new Rubro[]{Rubro.INDUSTRIA_MANUFACTURERA, Rubro.SERVICIO_DE_TRANSPORTE_Y_ALMACENAMIENTO,Rubro.INFORMACION_Y_COMUNICACIONES}),
    MINERIA(new Rubro[]{Rubro.EXPLOTACION_DE_MINAS, Rubro.CANTERAS}),
    AGROPECUARIO(new Rubro[]{Rubro.AGRICULTURA, Rubro.GANADERIA, Rubro.CAZA, Rubro.SILVICULTURA, Rubro.PESCA});

    private Rubro[] nombres;

    private Sector(Rubro[] nombres){
        this.nombres = nombres;
    }

    public Rubro[] getNombres(){
        return this.nombres;
    }
}
